version: '3'
services:

  captcha_solver_1:
    image: captcha:latest
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "1"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    ports:
      - 5052:5052
    restart: always
    command: gunicorn -c gunicorn.conf.py -b 0.0.0.0:5052 app:app

  captcha_solver_2:
    image: captcha:latest
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "1"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    ports:
      - 5053:5053
    restart: always
    command: gunicorn -c gunicorn.conf.py -b 0.0.0.0:5053 app:app

  captcha_nginx:
    image: nginx:latest
    ports:
      - 5051:5051
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - captcha_solver_1
      - captcha_solver_2

networks:
  default:
    driver: bridge