version: "3.8"

services:

  nginx:
    image: nginx:1.27
    container_name: captcha_nginx
    restart: always

    ports:
      - "5051:5051"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d

    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "1"

    networks:
      - default


networks:
  default:
    external:
      name: captcha